### ISSUE TITLE
How to load a file in CSV format but the extension isn't CSV?

### ISSUE THREAD

**Issue by xiaodaigh** [queryverse/CSVFiles.jl#47] opened 2019-03-18 09:52 UTC
I have files that are in csv format but the extension isn't CSV. How do I read those files?

**Comment by davidanthoff** [comment] 2019-03-19 16:09
```julia
load(File(format"CSV", path))
```
I'm closing as a duplicate of https://github.com/queryverse/CSVFiles.jl/issues/36.

**Closed by davidanthoff** 2019-03-19 16:09 UTC
